# Generated by Django 4.1.7 on 2023-03-10 07:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('capital', models.CharField(max_length=100)),
                ('region', models.CharField(choices=[('EU', 'Europe'), ('AS', 'Asia'), ('AM', 'Americas'), ('AF', 'Africa'), ('OC', 'Oceania'), ('AQ', 'Antarctic')], max_length=100)),
                ('population', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('flag', models.URLField()),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('to_be_used_at', models.DateField(null=True)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('object_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('value', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserCountryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guessed', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GuessCountry.country')),
                ('user_score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GuessCountry.score')),
            ],
        ),
        migrations.AddField(
            model_name='score',
            name='countries',
            field=models.ManyToManyField(through='GuessCountry.UserCountryRecord', to='GuessCountry.country'),
        ),
    ]
