# Generated by Django 4.1.7 on 2023-03-01 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuessCountry', '0002_alter_score_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='used_in_rotation',
            field=models.BooleanField(default=False),
        ),
    ]
