# Generated by Django 4.1.7 on 2023-03-01 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GuessCountry', '0003_country_used_in_rotation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='used_in_rotation',
        ),
        migrations.CreateModel(
            name='CountryToDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('used_in_rotation', models.BooleanField(default=False)),
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='GuessCountry.country')),
            ],
        ),
    ]
