# Generated by Django 4.1.7 on 2023-03-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuessCountry', '0004_remove_country_used_in_rotation_countrytodate'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='to_be_used_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='CountryToDate',
        ),
    ]
