# Generated by Django 4.1.7 on 2023-03-01 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuessCountry', '0005_country_to_be_used_at_delete_countrytodate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='to_be_used_at',
            field=models.DateField(null=True),
        ),
    ]
